// SPDX-License-Identifier: MulanPSL-2.0
const {default: openapiTS, astToString} = require('openapi-typescript');

// CommonJS resolution also finds NODE_PATH in the read-only image check.
(async () => {
  const ast = await openapiTS(process.stdin, {defaultNonNullable: false});
  process.stdout.write('// Generated by scripts/api-types.py from FastAPI OpenAPI. DO NOT EDIT.\n' + astToString(ast));
})().catch(error => { console.error(error.message); process.exitCode = 1; });
