#!/usr/bin/env python3
# SPDX-FileCopyrightText: (C) 2026 openRuyi Project Contributors
# SPDX-License-Identifier: MulanPSL-2.0
"""Generate the frontend contract from FastAPI OpenAPI; --check detects drift."""
import argparse
import json
from pathlib import Path
import sys
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT/'backend'))
from tracker.api import create_app


def ts(schema):
    if '$ref' in schema:
        return schema['$ref'].rsplit('/', 1)[-1]
    for union, separator in [('anyOf', ' | '), ('oneOf', ' | '), ('allOf', ' & ')]:
        if union in schema:
            return '(' + separator.join(ts(x) for x in schema[union]) + ')'
    if 'const' in schema:
        return json.dumps(schema['const'])
    if 'enum' in schema:
        return ' | '.join(json.dumps(x) for x in schema['enum'])
    kind = schema.get('type')
    if kind == 'array':
        return 'Array<' + ts(schema.get('items', {})) + '>'
    if kind == 'object' or 'properties' in schema:
        required = schema.get('required', [])
        fields = [json.dumps(k) + ('' if k in required else '?') + ': ' + ts(v)
                  for k, v in schema.get('properties', {}).items()]
        additional = schema.get('additionalProperties')
        if additional is True:
            fields.append('[key: string]: unknown')
        elif isinstance(additional, dict):
            fields.append('[key: string]: ' + ts(additional))
        return '{ ' + '; '.join(fields) + ' }'
    return {'integer':'number', 'number':'number', 'boolean':'boolean',
            'string':'string', 'null':'null'}.get(kind, 'unknown')


def render():
    document = create_app().openapi()
    schemas = document['components']['schemas']
    # The website compiles against reading documents only. Provider/domain
    # payloads remain published in OpenAPI, but are not frontend dependencies.
    selected = set()

    def visit(value):
        if isinstance(value, dict):
            reference = value.get('$ref')
            if reference:
                name = reference.rsplit('/', 1)[-1]
                if name not in selected:
                    selected.add(name)
                    visit(schemas[name])
            for child in value.values():
                visit(child)
        elif isinstance(value, list):
            for child in value:
                visit(child)

    for path, operations in document['paths'].items():
        if path.startswith('/api/ui/'):
            visit(operations['get']['responses']['200'])
    return ('// Generated by scripts/api-types.py from FastAPI OpenAPI. DO NOT EDIT.\n'
            '// Change backend response models, regenerate, and review the contract diff.\n'
            + ''.join(f'export type {name} = {ts(schemas[name])};\n' for name in sorted(selected)))


def main():
    p = argparse.ArgumentParser(description=__doc__); p.add_argument('--check', action='store_true')
    args = p.parse_args(); output = ROOT/'frontend/src/lib/api.generated.ts'; expected = render()
    if args.check:
        if not output.is_file() or output.read_text() != expected:
            print('API contract drift: run python scripts/api-types.py', file=sys.stderr); return 1
        print('API contract matches OpenAPI'); return 0
    output.write_text(expected); print(output); return 0


if __name__ == '__main__':
    raise SystemExit(main())
