// Generated by scripts/api-types.py from FastAPI OpenAPI. DO NOT EDIT.
// Change backend response models, regenerate, and review the contract diff.
export type Cell = { "lines": Array<Array<Text>> };
export type Choice = { "appearance": (string | null); "icon": (string | null); "label": string; "href": (string | null); "selected": boolean; "count": (number | null) };
export type Column = { "title": string; "role": "identity" | "value" | "status" };
export type Condition = { "dimension": string; "value": string; "logic": "and" | "or" };
export type Controls = { "editor": FilterEditor; "action": string; "query": string; "hidden": Array<Parameter>; "active": Array<Choice>; "navigation": Array<Navigation>; "choice_rows": Array<Navigation> };
export type DetailDocument = { "schema_version": 1; "title": string; "subtitle": (string | null); "identity": Array<Text>; "links": Array<Text>; "context": Array<Section>; "sections": Array<Section>; "notices": Array<string> };
export type DocumentTheme = { "appearances": { [key: string]: Palette } };
export type Entry = { "heading": Array<Text>; "fields": Array<Field> };
export type Field = { "label": string; "href": (string | null); "values": Array<Text> };
export type FilterCondition = { "appearance": (string | null); "icon": (string | null); "label": string; "href": (string | null); "selected": boolean; "count": (number | null); "logic": string };
export type FilterEditor = { "query": FilterQuery; "active_group": number; "node_limit": number; "groups": Array<FilterGroup>; "operators": Array<Choice>; "clear": string };
export type FilterGroup = { "id": number; "active": boolean; "select": string; "logic": string; "conditions": Array<FilterCondition>; "clear": string; "add": (string | null) };
export type FilterQuery = { "groups": Array<Group> };
export type Group = { "logic": "and" | "or"; "conditions": Array<Condition> };
export type ListingDocument = { "schema_version": 1; "title": string; "navigation": Navigation; "global_navigation": Array<Navigation>; "controls": Controls; "table": Table; "total": number; "page": number; "pages": number; "pagination": Array<Choice>; "meta": Array<Field>; "notices": Array<string> };
export type Navigation = { "label": string; "show_label": boolean; "icon": (string | null); "choices": Array<Choice> };
export type Palette = { "background": string; "foreground": string };
export type Parameter = { "name": string; "value": string };
export type Row = { "key": string; "id": (string | null); "cells": Array<Cell>; "notes": Array<RowNote> };
export type RowNote = { "column": number; "span": number; "values": Array<Text> };
export type Section = { "id": string; "title": string; "collapsible": boolean; "fields": Array<Field>; "table": (Table | null); "entries": Array<Entry>; "notes": Array<string> };
export type Table = { "label": string; "columns": Array<Column>; "rows": Array<Row>; "empty": string };
export type Text = { "text": string; "href": (string | null); "title": (string | null); "kind": "text" | "code" | "tag" | "time"; "variant": "outline" | "solid"; "tone": "normal" | "muted" | "positive" | "negative" | "notice"; "appearance": (string | null); "decoration": ("dashed" | null); "datetime": (string | null) };
