// Generated by scripts/api-types.py from FastAPI OpenAPI. DO NOT EDIT.
// Change backend response models, regenerate, and review the contract diff.
export type Cell = { "lines": Array<Array<Text>> };
export type Choice = { "label": string; "href": string; "selected": boolean; "count": (number | null) };
export type Column = { "title": string; "role": "identity" | "value" | "status" };
export type Controls = { "action": string; "query": string; "hidden": Array<Parameter>; "facets": Array<Facet>; "active": Array<Choice>; "navigation": Array<Navigation> };
export type DetailDocument = { "schema_version": 1; "title": string; "subtitle": (string | null); "identity": Array<Text>; "links": Array<Text>; "context": Array<Section>; "sections": Array<Section> };
export type DocumentTheme = { "appearances": { [key: string]: Palette } };
export type Entry = { "heading": Array<Text>; "fields": Array<Field> };
export type Facet = { "id": string; "name": string; "label": string; "options": Array<Option> };
export type Field = { "label": string; "values": Array<Text> };
export type ListingDocument = { "schema_version": 1; "title": string; "navigation": Navigation; "controls": Controls; "table": Table; "total": number; "page": number; "pages": number; "pagination": Array<Choice>; "meta": Array<Field>; "notices": Array<string> };
export type Navigation = { "label": string; "choices": Array<Choice> };
export type Option = { "value": string; "label": string; "count": (number | null); "selected": boolean };
export type Palette = { "background": string; "foreground": string };
export type Parameter = { "name": string; "value": string };
export type Row = { "key": string; "cells": Array<Cell> };
export type Section = { "id": string; "title": string; "collapsible": boolean; "fields": Array<Field>; "table": (Table | null); "entries": Array<Entry>; "notes": Array<string> };
export type Table = { "label": string; "columns": Array<Column>; "rows": Array<Row>; "empty": string };
export type Text = { "text": string; "href": (string | null); "title": (string | null); "kind": "text" | "code" | "tag" | "time"; "tone": "normal" | "muted" | "positive" | "negative" | "notice"; "appearance": (string | null); "datetime": (string | null) };
