// Generated by scripts/api-types.py from FastAPI OpenAPI. DO NOT EDIT.
export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Cell */
        Cell: {
            /**
             * Lines
             * @default []
             */
            lines: components["schemas"]["Text"][][];
        };
        /** Choice */
        Choice: {
            /** Appearance */
            appearance: string | null;
            /** Icon */
            icon: string | null;
            /** Label */
            label: string;
            /** Href */
            href: string | null;
            /**
             * Selected
             * @default false
             */
            selected: boolean;
            /** Count */
            count: number | null;
        };
        /** Column */
        Column: {
            /** Title */
            title: string;
            /**
             * Role
             * @default value
             * @enum {string}
             */
            role: "identity" | "value" | "status";
        };
        /** Condition */
        Condition: {
            /** Dimension */
            dimension: string;
            /** Value */
            value: string;
            /**
             * Logic
             * @default and
             * @enum {string}
             */
            logic: "and" | "or" | "not";
        };
        /** Controls */
        Controls: {
            editor: components["schemas"]["FilterEditor"];
            /**
             * Action
             * @default /
             */
            action: string;
            /**
             * Query
             * @default
             */
            query: string;
            /**
             * Hidden
             * @default []
             */
            hidden: components["schemas"]["Parameter"][];
            /**
             * Active
             * @default []
             */
            active: components["schemas"]["Choice"][];
            /**
             * Navigation
             * @default []
             */
            navigation: components["schemas"]["Navigation"][];
            /**
             * Choice Rows
             * @default []
             */
            choice_rows: components["schemas"]["Navigation"][];
        };
        /** DetailDocument */
        DetailDocument: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Title */
            title: string;
            /** Subtitle */
            subtitle: string | null;
            /**
             * Identity
             * @default []
             */
            identity: components["schemas"]["Text"][];
            /**
             * Links
             * @default []
             */
            links: components["schemas"]["Text"][];
            /**
             * Context
             * @default []
             */
            context: components["schemas"]["Section"][];
            /** Sections */
            sections: components["schemas"]["Section"][];
            /**
             * Notices
             * @default []
             */
            notices: string[];
        };
        /** DocumentTheme */
        DocumentTheme: {
            /**
             * Appearances
             * @default {}
             */
            appearances: {
                [key: string]: components["schemas"]["Palette"];
            };
        };
        /** Entry */
        Entry: {
            /** Heading */
            heading: components["schemas"]["Text"][];
            /**
             * Metadata
             * @default []
             */
            metadata: components["schemas"]["Text"][];
            /**
             * Fields
             * @default []
             */
            fields: components["schemas"]["Field"][];
        };
        /** Field */
        Field: {
            /** Label */
            label: string;
            /** Href */
            href: string | null;
            /** Values */
            values: components["schemas"]["Text"][];
        };
        /** FilterCondition */
        FilterCondition: {
            /** Appearance */
            appearance: string | null;
            /** Icon */
            icon: string | null;
            /** Label */
            label: string;
            /** Href */
            href: string | null;
            /**
             * Selected
             * @default false
             */
            selected: boolean;
            /** Count */
            count: number | null;
            /** Logic */
            logic: string;
        };
        /** FilterEditor */
        FilterEditor: {
            query: components["schemas"]["FilterQuery"];
            advanced: components["schemas"]["Choice"];
            /** Node Count */
            node_count: number;
            /**
             * Node Limit
             * @default 128
             */
            node_limit: number;
            /** Groups */
            groups: components["schemas"]["FilterGroup"][];
            /** Operators */
            operators: components["schemas"]["Choice"][];
            /** Group */
            group: string | null;
            /** Clear */
            clear: string;
        };
        /** FilterGroup */
        FilterGroup: {
            /** Id */
            id: number;
            /** Closed */
            closed: boolean;
            /** Palette */
            palette: (0 | 1 | 2 | 3) | null;
            /** Logic */
            logic: string;
            /** Conditions */
            conditions: components["schemas"]["FilterCondition"][];
            /** Clear */
            clear: string | null;
        };
        /** FilterQuery */
        FilterQuery: {
            /**
             * Mode
             * @default advanced
             * @enum {string}
             */
            mode: "basic" | "advanced";
            /**
             * Groups
             * @default []
             */
            groups: components["schemas"]["Group"][];
            /**
             * Tail
             * @default []
             */
            tail: components["schemas"]["Condition"][];
        };
        /** Group */
        Group: {
            /**
             * Logic
             * @default and
             * @enum {string}
             */
            logic: "and" | "or" | "not";
            /**
             * Conditions
             * @default []
             */
            conditions: components["schemas"]["Condition"][];
        };
        /** ListingDocument */
        ListingDocument: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Title */
            title: string;
            navigation: components["schemas"]["Navigation"];
            /**
             * Global Navigation
             * @default []
             */
            global_navigation: components["schemas"]["Navigation"][];
            controls: components["schemas"]["Controls"];
            table: components["schemas"]["Table"];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Pages */
            pages: number;
            /**
             * Pagination
             * @default []
             */
            pagination: components["schemas"]["Choice"][];
            /**
             * Meta
             * @default []
             */
            meta: components["schemas"]["Field"][];
            /**
             * Notices
             * @default []
             */
            notices: string[];
        };
        /** Navigation */
        Navigation: {
            /** Label */
            label: string;
            /**
             * Show Label
             * @default true
             */
            show_label: boolean;
            /** Icon */
            icon: string | null;
            /** Choices */
            choices: components["schemas"]["Choice"][];
        };
        /** Palette */
        Palette: {
            /** Background */
            background: string;
            /** Foreground */
            foreground: string;
        };
        /** Parameter */
        Parameter: {
            /** Name */
            name: string;
            /** Value */
            value: string;
        };
        /** Row */
        Row: {
            /** Key */
            key: string;
            /** Id */
            id: string | null;
            /** Cells */
            cells: components["schemas"]["Cell"][];
            /**
             * Notes
             * @default []
             */
            notes: components["schemas"]["RowNote"][];
        };
        /** RowNote */
        RowNote: {
            /** Column */
            column: number;
            /** Span */
            span: number;
            /** Values */
            values: components["schemas"]["Text"][];
        };
        /** Section */
        Section: {
            /**
             * Placement
             * @default flow
             * @enum {string}
             */
            placement: "flow" | "lead" | "aside";
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Collapsible
             * @default false
             */
            collapsible: boolean;
            /** More */
            more: string | null;
            /**
             * Fields
             * @default []
             */
            fields: components["schemas"]["Field"][];
            table: components["schemas"]["Table"] | null;
            /**
             * Entries
             * @default []
             */
            entries: components["schemas"]["Entry"][];
            /**
             * Notes
             * @default []
             */
            notes: string[];
        };
        /** Table */
        Table: {
            /** Label */
            label: string;
            /** Columns */
            columns: components["schemas"]["Column"][];
            /** Rows */
            rows: components["schemas"]["Row"][];
            /**
             * Empty
             * @default No matching packages.
             */
            empty: string;
        };
        /** Text */
        Text: {
            /** Text */
            text: string;
            /** Href */
            href: string | null;
            /** Title */
            title: string | null;
            /**
             * Kind
             * @default text
             * @enum {string}
             */
            kind: "text" | "code" | "tag" | "time";
            /**
             * Variant
             * @default outline
             * @enum {string}
             */
            variant: "outline" | "solid";
            /**
             * Tone
             * @default normal
             * @enum {string}
             */
            tone: "normal" | "muted" | "positive" | "negative" | "notice";
            /** Appearance */
            appearance: string | null;
            /** Decoration */
            decoration: "dashed" | null;
            /** Datetime */
            datetime: string | null;
            /** Icon */
            icon: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
